# Generated by Django 5.2.7 on 2025-12-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='read_time',
        ),
        migrations.AddField(
            model_name='post',
            name='by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
